smol-ai/GodMode

- index.html
issue: pasting text into the inner webview would result in the text appearing twice. this was due to electron's handling of paste events in webviews which under certain conditions might trigger the event twice
to circumvent this a flag has been introduced to intercept and ignore every second paste event
https://github.com/smol-ai/menubar/assets/90765930/d603c75f-4cfd-431e-8e0b-2fd123cfebb3
> fix: double paste inside webviews

- index.html
issue: looks like the paste event was getting triggered more than twice for some users
this PR debounces these events, ensuring only one paste of the same text occurs within 100ms
> fix: debounce inner paste event

- index.html
- preferences.html
- preferences.js
In previous versions, I found it convenient to only use the "Enter" key in the super prompt. I'm adding an option to allow users to use either the "Enter" key or "CMD+Enter" keys in the super prompt.
> Add option to use "Enter" key instead of "CMD+Enter" keys in super prompt

- index.html
- index.js
issue: The application's WebView instances were triggering the 'paste' event more than once when the user attempted to paste text. This occurred because both Electron and the web content inside the WebView were handling the paste event, causing duplicate actions
solution:
- removed Electron's 'paste' action listener from WebView instances in the main process. By commenting out the line 
`if (key === "v") contents.paste()` 
we stopped Electron from handling paste events at the application level.
- injected JavaScript into each WebView to capture the 'paste' event before it reaches Electron. This JavaScript prevents the default paste behavior, extracts the pasted text from the ClipboardData object, and pastes it manually into the focused element …
> fix: duplicate paste proper fix

- interface.js
For Chinese language, there is a suggestion window that appears when the input is incomplete, and it remains until the user makes a choice. Therefore, the Input Event Listener is edited to handle this.
> pr: handle the input event for composition input methods like Chinese

- providers/bing.js
- providers/claude2.js
- providers/openai.js
This PR:
- Forces Chat GPT into dark mode
- Does CSS changes to create a dark mode for bing and Claude 2
- Deletes some unnecessary UI clutter from Claude and Bing
Much better experience on smaller screens now imo! Please take a look and merge if you agree!
> Dark mode and CSS cleanup for claude, bing, and chatGPT

- README.md
- index.js
I noticed that I'm spending a lot of time dragging to resize the menubar to make it fullscreen. With this small update, you can hit `Cmd` + `Shift` + `F` (which is conveniently right next to `Cmd` + `Shift` + `G`!) to toggle back and forth between full viewport width and the default 1200 pixel width.
Great for people on ultra-wide monitors, you can probably now easily fit 6 or 7 providers side-by-side.
This demo video shows it on my laptop screen but I can take another one on my super-wide monitor when I get a chance if we think it's worth sharing!
https://github.com/smol-ai/menubar/assets/882952/21056599-4657-4a25-b622-252a3b7654a7
> add support for fullscreen toggle + keyboard shortcut

- index.css
- index.js
Something that was bothering me is that the windows were rounded but the prompt bar was not so I changed that. Also
- prompt bar changes color when in focus. @swyxio feel free to change the color
- The margin between the left hand side and the right hand side of the prompt bar is now equal (box sizing border box lol)
If you want I can implement the design from #24 entirely
> Better styling for the superprompt bar

- index.css
- index.html
- index.js
- interface.js
- An implementation of #24 
- I took inspiration that the menubar menu gives an easy way to toggle sites on and off so didn't implement the tabs. Most of the time I wanna see the output and the tabs would take up space
- The arrow icon would make it less intuitive that cmd+enter submits the query so I kept the text as is.
> Design upgrade for superprompt bar

- .prettierrc.json
- CONTRIBUTING.md
- index.js
- interface.js
- package-lock.json
- package.json
- providers/bard.js
- providers/bing.js
- providers/claude.js
- providers/claude2.js
- providers/huggingchat.js
- providers/oobabooga.js
- providers/openai.js
- providers/provider.js
- providers/smol.js
- setup.js
- src/panes.js
There's a mixture of tabs and spaces which messed with my indentation a bit so I added a prettier file.
It seems like most files were in tabs so I also went with tabs.
Feel free to discard this if you don't want it. It might cause a bunch of merge issues if there are a lot of PRs in progress so might be best to do this some other time.
> chore: Format using prettier

- index.js
With this change, menubar will no longer dismiss when it loses focus in development mode, which means the webview-specific dev tools windows will also stay open and be interactive! So this is a small fix that will make debugging a lot more pleasant.
> feat(index) menubar stays open in development for debugging

- README.md
- index.js
Turns out people have window managers. 🙃
> remove fullscreen mode keyboard shortcut; resolves #102, repeals #68

- index.css
- index.html
- interface.js
i also tried to add a vertical gutter, but the gutter showed up but couldnt get the resizing to work, so i dropped it since nobody's really asking for it
> minor tweaks to split gutter

- index.css
- index.html
- index.js
- interface.js
- providers/huggingchat.js
- providers/openai.js
- providers/phind.js
- providers/smol.js
- src/panes.js
this looks ugly now but just shipping a way to clear cookies for smol talk ahead of the smol gods rewrite
> Minor touchups for smol talk, abilty to go back/forward in browser history

- CONTRIBUTING.md
- README.md
- package.json
- src/renderer/browserPane.tsx
Not sure if this really matters given GH's redirecting, so happy to pull back on this. I think keeping the cd GodMode instruction in the README is valuable though.
I didn't change any of the apple signing instructions, as I haven't tested them and didn't want to unintentionally break the workflow.
> docs: fix references to menubar

- README.md
- src/main/main.ts
- src/main/preload.ts
- src/renderer/components/settings.tsx
- Add "Open at Login" feature
- Modify settings menu to allow for open at login toggle
Response to #145
> Add Open at Login

- src/main/main.ts
Enable Godmode to open URLs in users' default browsers. Check issue: #149. 
Instead of overriding the electron window every time a link is clicked, Godmode can now open one or multiple links in users' default browsers.
I enabled Godmode to open any link in the users' default browsers by adding an app listener to the contents of Godmode.
> URLs should open in system browser

- src/renderer/layout.tsx
Add window switch shortcut using digit keys for all keyboard layouts. You can now switch between windows using the ⌘ (Command) or CTRL key in combination with the digit keys, regardless of your keyboard layout.
**Fixes:** #158
> fix: window switch on all keyboard layouts

- src/components/pane.tsx
- src/main/main.ts
- src/providers/bard.js
- src/renderer/layout.tsx
fixes bard issue seen in #225  
also  fixes #220 (@0xAsynchronous) and fixes #221
fixes #218 @alfonmga
my issues fixes #215
> get bard working, demote from default. other minor UX fixups 

- src/renderer/layout.tsx
Fix zoom in edge case when a user navigates to a window pane with a keyboard shortcut. 
Now it matches the same behaviour as when we click the button inside of the pane.
Fix https://github.com/smol-ai/GodMode/issues/215#issuecomment-1708496188
> fix: zoom in with keyboard shortcut

- src/lib/constants.ts
- src/providers/falcon180bspace.js
https://huggingface.co/blog/falcon-180b
> add falcon 180b

- README.md
- src/providers/perplexity-llama.js
- src/providers/perplexity.js
Fixes #203.
User agent was copied from the claude2 provider.
I also updated the readme to remove the electron squirrel instructions, as I've never installed electron or the squirrel package, and had no issues setting up and running this repo on windows 11.
> fix: use a different user agent to ensure perplexity loads on windows

- package-lock.json
- src/lib/types.ts
- src/main/main.ts
- src/main/preload.ts
- src/renderer/components/settings.tsx
Adds a toggle switch to the settings menu for toggling superprompt input focus on quickopen shortcut. 
The default would be `false`, like the behavior is currently. 
Implementation of #251
> feat: add superprompt focus on quickopen shortcut

- src/providers/poe.js
**Issue:**
The `handleSubmit` function in the poe provider had an issue with the button selector, causing it to fail when submitting. This happens because the class names include a generated string at the end of them.
**Solution:**
Fixed the button selector by checking for a substring of a class excluding the generated string.
> fix: poe submit button selector
