smol-ai/GodMode

index.css, index.html
https://github.com/smol-ai/menubar/assets/90765930/3a6b5e05-3946-4963-b52c-20d6a5c2855b
text area, cmd+enter, can scroll, can paste into it, render newlines correctly inside the webviews inputs
=> cosmetic fixes

index.html, index.js, package-lock.json, package.json, preferences.html, preferences.js
I'm using this app a lot, will keep monitoring how i'm using it and what pain points i have 😄 
- added a preferences view that allows picking which models to use, and persisting this using electron-store
- the previous shortcuts for cmd+1/2/3/a will now also use this store and persist preferences
https://github.com/smol-ai/menubar/assets/90765930/66e06e1f-574b-494c-91b1-75ea314b3fe3
=> feat: persist preferences

index.html
Fix: bard issue with event delays messing button enable/disable and multi-line text input
https://github.com/smol-ai/menubar/assets/3692138/32bffad9-7f7c-47bd-b591-6fa3f3c9af94
=> Fix: bard issue with event

index.html, index.js
fix: feat: update accelerator label and autofocus input on load
=> Fix: Feat: #21 and autofocus input on load

index.html, package-lock.json, providers/openai.js
Potential solve for preloading gpt-4 in smol menubar: https://github.com/smol-ai/menubar/issues/51
Not sure what will happen if you don't have access to GPT-4
=> switch chatgpt to gpt4

README.md, index.js, interface.js, providers/oobabooga.js, providers/smol.js
closes #62. let me know if this readme works @seanoliver 
i explored using GPT4all which has a nicer UI and download experience, however their server mode https://docs.gpt4all.io/gpt4all_chat.html#server-mode does not seem to serve the UI (or frankly work at all for me)
=> add oobabooga to support local models

README.md, index.js, interface.js, providers/huggingchat.js
Adding support for HuggingChat. Resolves https://github.com/smol-ai/menubar/issues/36.
Note HuggingChat is disabled by default in this version.
Also I added a pretty sweet table to the README to really highlight all the providers we support.
=> Add hugging chat - Resolves #36

index.js, interface.js, providers/perplexity.js
Fixes #88
The store value was not correct for me when I used the `store` directly in the renderer. So I used IPC instead.
=> fix: Fullscreen keyboard shortcut should be local not global

providers/phind.js
btw, looks like there is a mixture of tabs and spaces used for indentation in this file, it makes it particularly annoying to do any changes :)
=> add followup ability to phind

README.md, index.js, interface.js, providers/phind.js
=> Add phind - resolves #39

index.js
Reverts smol-ai/menubar#97
Whoops! This is not quite ready for prime time. Apologies!
=> Revert "feat(index) menubar stays open in development for debugging"

index.js, interface.js, package-lock.json, providers/perplexity-llama.js, providers/phind.js
Hey all, 
I have been using menu bar for a while and I love it. Just didn't really enjoy using Hugging chat for llama-2-70b and instead prefer the perplexity labs version so I made a small PR to support that.
Also have fixed up a bug with Phind since they recently changed their placeholder text which rendered the current selector useless. 
Hope this helps!
=> Added the new Llama-2 Perplexity agent and fixed up phind bug

index.js
Reverts smol-ai/menubar#99 as it is clearly causing bugs
=> Revert "Dev mode"

index.js, interface.js, providers/poe.js
=> Added support for Poe

package-lock.json, package.json, src/components/pane.tsx, src/lib/types.ts, src/main/main.ts, src/providers/bing.js, src/providers/perplexity.js, src/renderer/App.css, src/renderer/browserPane.tsx, src/renderer/components/ui/dialog.tsx, src/renderer/components/ui/input.tsx, src/renderer/components/ui/tooltip.tsx, src/renderer/layout.tsx, tailwind.config.js
=> add browser pane popout thing

src/main/main.ts
Fixes bug with paste shortcut and summon from close. Resolves #133
=> Summon from close - resolves #133 

src/main/main.ts
however we might still want to offer multiple "windows"
=> make window a singleton = so you cant have multiple instances of the app live

src/components/pane.tsx, src/renderer/layout.tsx
adds a zoom reset function under `cmd + 0` a well as add the reset icon in the ui
=> implement zoom-reset as cmd+0 and button

src/lib/constants.ts, src/providers/inflection.js
Add Inflection Pi provider to allProviders list.
Make event submit correctly.
=> Fix Inflection Pi submit

src/components/pane.tsx, src/lib/utils.ts, src/renderer/layout.tsx
Commit log by fix/feature:
- fix(windows): allow global refresh command to work
- fix(windows): ensure refresh button in maximized panes works
- feat: add a util for getting the current platform
- feat: add a constant for Cmd or Ctrl based on the current platform
- feat: use cmd or ctrl appropriately in various UI text
I snuck in the last three commits, but am happy to make changes if that's reaching too far.
Fixes #171, fixes #172.
=> Fix various windows keyboard ailments

package-lock.json, package.json, src/main/main.ts
- Small change to add support for right-click context menus in the web views. This allows you to open the individual developer tools / console for each webview for debugging.
=> add support for context menus in individual webviews for debugging

src/main/main.ts, src/providers/bard.js
fixing the alarming issue with #201!
=> allowlist for SSO login domains, fix Google login

package-lock.json, src/providers/inflection.js
Updates the input selector to work after inflection have made changes to their ui.
Closes: #245
=> fix: inflection input selector

src/providers/openai.js
Update for the new openai view. Tested in local dev and works.
=> Update openai.js for new gpt ui update
